---
title: "6 vs 8 year olds"
author: "Meltem Ozcan"
date: "1/9/2022"
output: html_document
---


```{r, include=FALSE}
library(glmmTMB)
library(simr) #for makeGlmer
library(corpcor) #for make.pos.def
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reduced model 1
$$
\begin{align*}
\text{Y}_{i(j,k)}&=\gamma_{00} \\
                  &+\gamma_{10}\text{condition}_{j} \\
                  &+\gamma_{20}\text{information}_{j} \\
                  &+\gamma_{40}\text{age}_{k}\\
                  &+\gamma_{50}\text{gender}_k\\
                  &+\gamma_{60}\text{age}_k \times \text{gender}_k \\
                  &+\gamma_{11}\text{age}_{k}\times\text{condition}_{j} \\
                  &+\gamma_{21}\text{age}_{k}\times\text{information}_{j} \\
                  &+u_{0k} \\
                  &+u_{0j}
\end{align*}
$$

For 6 year olds,
$$
\begin{align*}
P(\text{complex}|\text{baby})=\dfrac{\text{exp}(\eta_{(j,k)})}{1+\text{exp}(\eta_{(j,k)})}&=\frac{1}{3}\\
2\times\text{exp}(\eta_{(j,k)})&=1\\
{\eta_{(j,k)}}_{|\text{baby}}&=-0.693\\
P(\text{complex}|\text{adult})=\dfrac{\text{exp}(\eta_{(j,k)})}{1+{\text{exp}(\eta_{(j,k)})}}&=\frac{2}{3}\\
\text{exp}(\eta_{(j,k)})&=2\\
{\eta_{(j,k)}}_{\text{|adult}}&=0.693\\
\end{align*}
$$

$$
\begin{align*}
{\eta_{(j,k)}}_{\text{adult}}-{\eta_{(j,k)}}_{\text{baby}}&=0.693+0.693\\
  1.386=&\gamma_{10}+\gamma_{11}\underbrace{\text{age}_{k}}_{0}\\
  1.386=&\gamma_{10}
\end{align*}
$$

For 8 year olds,

$$
\begin{align*}
P(\text{complex}|\text{adult})=\dfrac{\text{exp}(\eta_{(j,k)})}{1+\text{exp}(\eta_{(j,k)})}&=\frac{3}{4}\\
\text{exp}(\eta_{(j,k)})&=3\\
{\eta_{(j,k)}}_{|\text{adult}}&=1.099\\
P(\text{complex}|\text{baby})=\dfrac{\text{exp}(\eta_{(j,k)})}{1+{\text{exp}(\eta_{(j,k)})}}&=\frac{1}{4}\\
3\times\text{exp}(\eta_{(j,k)})&=1\\
{\eta_{(j,k)}}_{\text{baby}}&=-1.099\\
\end{align*}
$$

$$
\begin{align*}
{\eta_{(j,k)}}_{\text{adult}}-{\eta_{(j,k)}}_{\text{baby}}&=1.099+1.099\\
  2.198=&\gamma_{10}+\gamma_{11}\underbrace{\text{age}_{k}}_{1}\\
  2.198=&\gamma_{10}+\gamma_{11}
\end{align*}
$$







```{r counterbalance-prep}
condord1 <- c("Baby", "Adult", "Adult", "Baby",
              "Adult", "Baby", "Baby", "Adult",
              "Baby", "Adult", "Adult", "Baby")
condord2 <- c("Adult", "Baby", "Baby", "Adult",
              "Baby", "Adult", "Adult", "Baby",
              "Adult", "Baby", "Baby", "Adult")

animord1 <- c("Pa", "Be", "Ti", "Bi", "Ze", "Fo",
              "Ra", "Ho", "De", "Tu", "Du", "Go")
animord2 <- c("Go", "Du", "Tu", "De", "Ho", "Ra",
              "Fo", "Ze", "Bi", "Ti", "Be", "Pa")
animord3 <- c("Be", "Ti", "Ze", "Pa", "Tu", "Go",
              "Du", "Ra", "Fo", "Bi", "Ho", "De")
animord4 <- c("De", "Ho", "Bi", "Fo", "Ra", "Du", 
              "Go", "Tu", "Pa", "Ze", "Ti", "Be")
inford1 <- c(rep("CB", 3), rep("BC", 3), rep("CB", 3), rep("BC", 3))
inford2 <- c(rep("BC", 3), rep("CB", 3), rep("BC", 3), rep("CB", 3))
inford3 <- c(rep("BC", 3), rep("CB", 3), rep("CB", 3), rep("BC", 3))
inford4 <- c(rep("CB", 3), rep("BC", 3), rep("BC", 3), rep("CB", 3))
```

```{r n-64-dataset-fixed}
n = 32
child <- as.factor(rep(c(1:n), each = 12)  )
condition <- c(rep(condord1, 16), rep(condord2, 16))
animal <- rep(c(animord1, animord2, animord3, animord4), 8)
information <- rep(c(inford1, inford2, inford3, inford4), 8)
gender <- rep(c(rep("F", 12), rep("M", 12), rep("M", 12), rep("F", 12), 
            rep("M", 12), rep("F", 12), rep("F", 12), rep("M", 12)), 4)

#expand to have 2 age groups, assuming we'll have the same counterbalancing
child2 <- as.factor(rep(c(1:(n*2)), each = 12)  )

condition2 <- c(condition, condition)
animal2 <- c(animal, animal)
information2 <- c(information, information)
gender2 <- c(gender, gender)
age <- c(rep("6", n*12), rep("8", n*12))

df64 <- as.data.frame(cbind("child" = child2, "animal"= animal2, 
                           "information" = information2, 
                           "condition" = condition2,
                           "gender" = gender2, 
                           "age" = age))
df64["age01"] <- ifelse(df64$age==6,0,1)
df64["gender01"] <- ifelse(df64$gender=="M",0,1)
df64["condition01"] <- ifelse(df64$condition=="Baby",0,1)
df64["information01"] <- ifelse(df64$information=="BC",0,1)

head(df64)
```



```{r n-80-dataset-fixed}
n = 40
child <- as.factor(rep(c(1:n), each = 12))
condition <- c(rep(condord1, 20), rep(condord2, 20))
animal <- rep(c(animord1, animord2, animord3, animord4), 10)
information <- rep(c(inford1, inford2, inford3, inford4), 10)
gender <- rep(c(rep("F", 12), rep("M", 12)), 20)

#expand to have 2 age groups
child2 <- as.factor(rep(c(1:(n*2)), each = 12))

condition2 <- c(condition, condition)
animal2 <- c(animal, animal)
information2 <- c(information, information)
gender2 <- c(gender, gender)
age <- c(rep("6", n*12), rep("8", n*12))

df80 <- as.data.frame(cbind("child" = child2, "animal"= animal2, 
                           "information" = information2, 
                           "condition" = condition2,
                           "gender" = gender2, 
                           "age" = age))
df80["age01"] <- ifelse(df80$age==6,0,1)
df80["gender01"] <- ifelse(df80$gender=="M",0,1)
df80["condition01"] <- ifelse(df80$condition=="Baby",0,1)
df80["information01"] <- ifelse(df80$information=="BC",0,1)
```

```{r n-96-dataset-fixed}
n = 48 # per age group
child <- as.factor(rep(c(1:n), each = 12)  )
condition <- c(rep(condord1, 24), rep(condord2, 24))
animal <- rep(c(animord1, animord2, animord3, animord4), 12)
information <- rep(c(inford1, inford2, inford3, inford4), 12)
gender <- rep(c(rep("F", 12), rep("M", 12)), 24)
child2 <- as.factor(rep(c(1:(n*2)), each = 12))

condition2 <- c(condition, condition)
animal2 <- c(animal, animal)
information2 <- c(information, information)
gender2 <- c(gender, gender)
age <- c(rep("6", n*12), rep("8", n*12))

df96 <- as.data.frame(cbind("child" = child2, "animal"= animal2, 
                           "information" = information2, 
                           "condition" = condition2,
                           "gender" = gender2, 
                           "age" = age))
df96["age01"] <- ifelse(df96$age==6, 0, 1)
df96["gender01"] <- ifelse(df96$gender=="M",0,1)
df96["condition01"] <- ifelse(df96$condition=="Baby",0,1)
df96["information01"] <- ifelse(df96$information=="BC",0,1)
```

## Functions

```{r gen-dataset-reduced1-func}
gen_dataset_red1 <- function(gamma00, gamma20, gamma40, gamma50, gamma60, 
                          gamma11, gamma21, gamma10_6, gamma10_8,
                          tau0jsq_6, tau0j0k_6, tau0ksq_6, 
                          tau0jsq_8, tau0j0k_8, tau0ksq_8,
                          df) {
  
info <- df$information01; cond <- df$condition01; age <- df$age01
gender <- df$gender01
   
# Generate the random components
covar_matrix_6 <- make.positive.definite(matrix(c(tau0jsq_6, tau0j0k_6,
                         tau0j0k_6, tau0ksq_6), ncol = 2), tol=1e-3)
random_comp_6 <- MASS::mvrnorm(n = 1, mu = c(0, 0), Sigma = covar_matrix_6)
u0j_6 <- random_comp_6[1]; u0k_6 <- random_comp_6[2]

covar_matrix_8 <- make.positive.definite(matrix(c(tau0jsq_8, tau0j0k_8, 
                         tau0j0k_8, tau0ksq_8), ncol = 2), tol=1e-3)
random_comp_8 <- MASS::mvrnorm(n = 1, mu = c(0, 0), Sigma = covar_matrix_8)
u0j_8 <- random_comp_8[1]; u0k_8 <- random_comp_8[2]

# Probabilities
eta_6_comp_adult <- gamma00 + gamma10_6 + gamma20*info + gamma40*age + 
  gamma50*gender + gamma60*age*gender + 
  gamma11*age + gamma21*age*info + u0j_6 + u0k_6

eta_6_comp_baby <- gamma00 + gamma20*info + gamma40*age +
  gamma50*gender + gamma60*age*gender + gamma21*age*info +
  u0j_6 + u0k_6

eta_8_comp_adult <- gamma00 + gamma10_8 + gamma20*info + 
  gamma40*age + gamma50*gender + gamma60*age*gender + 
  gamma11*age + gamma21*age*info + u0j_8 + u0k_8 

eta_8_comp_baby <- gamma00 + gamma20*info + gamma40*age +
  gamma50*gender + gamma60*age*gender + gamma21*age*info +
  u0j_8 + u0k_8 

p_6y_complex_adult <- exp(eta_6_comp_adult) / (1 + exp(eta_6_comp_adult))
p_6y_basic_baby <- 1 - exp(eta_6_comp_baby) / (1 + exp(eta_6_comp_baby))

p_8y_complex_adult <- exp(eta_8_comp_adult) / (1 + exp(eta_8_comp_adult))
p_8y_basic_baby <- 1 - exp(eta_8_comp_baby) / (1 + exp(eta_8_comp_baby))

df["y"] <- c(rep(NA, dim(df)[1]))

for (i in seq_along(1:dim(df)[1])) {
  if (df[i, "age"]=="6"){
    if (df[i, "condition"]=="adult") {
      df[i, "y"] <- as.numeric(rbinom(1, 1, p_6y_complex_adult))
      } else {
      df[i, "y"] <- as.numeric(rbinom(1, 1, p_6y_basic_baby))
      }
  }
  if (df[i, "age"]=="8"){
    if (df[i, "condition"]=="adult") {
      df[i, "y"] <- as.numeric(rbinom(1, 1, p_8y_complex_adult))
      } else {
      df[i, "y"] <- as.numeric(rbinom(1, 1, p_8y_basic_baby))
      }
  }
}
return(df)
}
```


```{r gen-dataset-reduced2-func}
gen_dataset_red2 <- function(gamma00, gamma40,  gamma11, gamma10_6, gamma10_8, 
                             tau0jsq_6, tau0j0k_6, tau0ksq_6, 
                             tau0jsq_8, tau0j0k_8, tau0ksq_8,
                             df) {
info <- df$information01; cond <- df$condition01; age <- df$age01
gender <- df$gender01

# Generate the random components
covar_matrix_6 <- make.positive.definite(matrix(c(tau0jsq_6, tau0j0k_6,
                         tau0j0k_6, tau0ksq_6), ncol = 2), tol=1e-3)
random_comp_6 <- MASS::mvrnorm(n = 1, mu = c(0, 0), Sigma = covar_matrix_6)
u0j_6 <- random_comp_6[1]; u0k_6 <- random_comp_6[2]

covar_matrix_8 <- make.positive.definite(matrix(c(tau0jsq_8, tau0j0k_8, 
                         tau0j0k_8, tau0ksq_8), ncol = 2), tol=1e-3)
random_comp_8 <- MASS::mvrnorm(n = 1, mu = c(0, 0), Sigma = covar_matrix_8)
u0j_8 <- random_comp_8[1]; u0k_8 <- random_comp_8[2]

# Probabilities

eta_6_comp_adult <- gamma00 + gamma10_6 + gamma40*age + gamma11*age + u0j_6 + u0k_6 
eta_6_comp_baby <- gamma00 + gamma40*age + u0j_6 + u0k_6 

eta_8_comp_adult <- gamma00 + gamma10_8 + gamma40*age + gamma11*age  + u0j_8 + u0k_8
eta_8_comp_baby <- gamma00 +  gamma40*age + u0j_8 + u0k_8 

p_6y_complex_adult <- exp(eta_6_comp_adult) / (1 + exp(eta_6_comp_adult))
p_6y_basic_baby <- 1 - exp(eta_6_comp_baby) / (1 + exp(eta_6_comp_baby))

p_8y_complex_adult <- exp(eta_8_comp_adult) / (1 + exp(eta_8_comp_adult))
p_8y_basic_baby <- 1 - exp(eta_8_comp_baby) / (1 + exp(eta_8_comp_baby))

df["y"] <- c(rep(NA, dim(df)[1]))

for (i in seq_along(1:dim(df)[1])) {
  if (df[i, "age"]=="6"){
    if (df[i, "condition"]=="adult") {
      df[i, "y"] <- as.numeric(rbinom(1, 1, p_6y_complex_adult))
      } else {
      df[i, "y"] <- as.numeric(rbinom(1, 1, p_6y_basic_baby))
      }
  }
  if (df[i, "age"]=="8"){
    if (df[i, "condition"]=="adult") {
      df[i, "y"] <- as.numeric(rbinom(1, 1, p_8y_complex_adult))
      } else {
      df[i, "y"] <- as.numeric(rbinom(1, 1, p_8y_basic_baby))
      }
  }
}
return(df)
}
```


```{r set-parameters}
gamma00 <- 0
gamma20 <- 0.001 
gamma40 <- 1.5
gamma50 <-  0.001
gamma60 <- 0.01
gamma21 <- 0.001
gamma10_6 <- 1.386
gamma10_8 <- 1.099
gamma11_8 <- 1.099
  
# random comp
tau0jsq_6 <- 0.2
tau0j0k_6 <- 0
tau0ksq_6 <- 1
tau0jsq_8 <- 0.2
tau0j0k_8 <-0
tau0ksq_8 <- 1.5

niter = 1000
```




# Simulate data, compute power 

```{r red1-df64, message=FALSE, warning=FALSE}
set.seed(777)
datsets8_1_64 <- models8_1_64 <-  sig8_1_64 <- vector(mode="list", niter)
try(
for (i in 1:(niter)){
  datsets8_1_64[[i]] <- gen_dataset_red1(gamma00, gamma20, gamma40, 
                                   gamma50, gamma60, gamma11, 
                                   gamma21, gamma10_6, gamma10_8, 
                                   tau0jsq_6, tau0j0k_6, tau0ksq_6, 
                                   tau0jsq_8, tau0j0k_8, tau0ksq_8, df=df64)
  models8_1_64[[i]] <- summary(glmmTMB(y ~ condition01 + information01 + age01 +
                                   gender01 + age01*gender01 + age01*condition01 +
                                   age01*information01 + (1 | animal) + (1 | child),
                                   data = datsets8_1_64[[i]],
                                   family = binomial("logit"),
                                   REML = TRUE))
  sig8_1_64[i] <- models8_1_64[[i]]$coefficients[[1]][28]
}
)
sum(as.numeric(unlist(sig8_1_64)<0.05))/1000
#712/1000
```

```{r red1-df64-gamma11-10diff, message=FALSE, warning=FALSE}
set.seed(777)
gamma11 <- 1.6485
gamma10_8 <- 0.5495

datsets8_1_64_g <- models8_1_64_g <-  sig8_1_64_g <- vector(mode="list", niter)
try(
for (i in 1:(niter)){
  datsets8_1_64_g[[i]] <- gen_dataset_red1(gamma00, gamma20, gamma40, 
                                      gamma50, gamma60, gamma11, 
                                      gamma21, gamma10_6, gamma10_8, 
                                      tau0jsq_6, tau0j0k_6, tau0ksq_6, 
                                      tau0jsq_8, tau0j0k_8, tau0ksq_8, df=df64)
  models8_1_64_g[[i]] <- summary(glmmTMB(y ~ condition01 + information01 + age01 +
                                   gender01 + age01*gender01 + age01*condition01 +
                                   age01*information01 + (1 | animal) + (1 | child),
                                   data = datsets8_1_64_g[[i]],
                                   family = binomial("logit"),
                                   REML = TRUE))
  sig8_1_64_g[i] <- models8_1_64_g[[i]]$coefficients[[1]][28]
}
)
sum(as.numeric(unlist(sig8_1_64_g)<0.05))/1000


gamma10_8 <- 1.099
gamma11 <- 1.099

#712/1000
```

```{r red1-df64-no-age-info-int, message=FALSE, warning=FALSE}
set.seed(777)
# removing the interaction term of age and information order
datsets8_1_64_inf <- models8_1_64_inf <- sig8_1_64_inf <- vector(mode="list", niter)
try(
for (i in 1:(niter)){
  datsets8_1_64_inf[[i]] <- gen_dataset_red1(gamma00, gamma20, gamma40, 
                                   gamma50, gamma60, gamma11, 
                                   gamma21, gamma10_6, gamma10_8, 
                                   tau0jsq_6, tau0j0k_6, tau0ksq_6, 
                                   tau0jsq_8, tau0j0k_8, tau0ksq_8, df=df64)
  models8_1_64_inf[[i]] <- summary(glmmTMB(y ~ condition01 + information01 + age01 +
                                   gender01 + age01*gender01 + age01*condition01 +
                                   (1 | animal) + (1 | child),
                                   data = datsets8_1_64_inf[[i]],
                                   family = binomial("logit"),
                                   REML = TRUE))
  sig8_1_64_inf[i] <- models8_1_64_inf[[i]]$coefficients[[1]][25]
}
)
sum(as.numeric(unlist(sig8_1_64_inf)<0.05))/1000

#749/1000
```


```{r red2-df64,message=FALSE, warning=FALSE}
set.seed(777)
datsets8_2_64 <- models8_2_64 <- sig8_2_64 <- vector(mode="list", niter)
try(
for (i in 1:(niter)){
    datsets8_2_64[[i]] <- gen_dataset_red2(gamma00, gamma40,  gamma11, 
                                      gamma10_6, gamma10_8, 
                                      tau0jsq_6, tau0j0k_6, tau0ksq_6, 
                                      tau0jsq_8, tau0j0k_8, tau0ksq_8,df=df64)
  models8_2_64[[i]] <- summary(glmmTMB(y ~ condition01 + age01 + age01*condition01 +
                                    (1 | animal) + (1 | child),
                                    data = datsets8_2_64[[i]],
                                    family = binomial("logit"),
                                    REML = TRUE))
  sig8_2_64[i] <- models8_2_64[[i]]$coefficients[[1]][15]
}
)
sum(as.numeric(unlist(sig8_2_64)<0.05))/1000
#786/1000
```




```{r red1-df80, message=FALSE, warning=FALSE}
set.seed(777)
datsets8_1_80 <- models8_1_80 <- sig8_1_80 <- vector(mode="list", niter)
try(
for (i in 1:(niter)){
  datsets8_1_80[[i]] <- gen_dataset_red1(gamma00, gamma20, gamma40, gamma50, gamma60, 
                          gamma11, gamma21, gamma10_6, gamma10_8,
                          tau0jsq_6, tau0j0k_6, tau0ksq_6, 
                          tau0jsq_8, tau0j0k_8, tau0ksq_8, df=df80)
  models8_1_80[[i]] <- summary(glmmTMB(y ~ condition01 + information01 + age01 +
                                   gender01 + age01*gender01 + age01*condition01 +
                                   age01*information01 + (1 | animal) + (1 | child),
                                   data = datsets8_1_80[[i]],
                                   family = binomial("logit"),
                                   REML = TRUE))
  sig8_1_80[i] <- models8_1_80[[i]]$coefficients[[1]][28]
}
)
sum(as.numeric(unlist(sig8_1_80)<0.05))/1000
#746/1000
```


```{r red2-df80, message=FALSE, warning=FALSE}
set.seed(77)
datsets8_2_80 <- models8_2_80 <- sig8_2_80 <- vector(mode="list", niter)
try(
for (i in 1:(niter)){
  datsets8_2_80[[i]] <- gen_dataset_red2(gamma00, gamma40,  gamma11, 
                                      gamma10_6, gamma10_8, 
                                      tau0jsq_6, tau0j0k_6, tau0ksq_6, 
                                      tau0jsq_8, tau0j0k_8, tau0ksq_8, df=df80)
  models8_2_80[[i]] <- summary(glmmTMB(y ~ condition01 + age01 + age01*condition01 +
                                    (1 | animal) + (1 | child),
                                    data = datsets8_2_80[[i]],
                                    family = binomial("logit"),
                                    REML = TRUE))
  sig8_2_80[i] <- models8_2_80[[i]]$coefficients[[1]][15]
}
)
sum(as.numeric(unlist(sig8_2_80)<0.05))/1000
#824/1000
```




```{r red1-df96, message=FALSE, warning=FALSE}
set.seed(777)
datsets8_1_96 <- models8_1_96 <-  sig8_1_96 <- vector(mode="list", niter)
try(
for (i in 1:(niter)){
  datsets8_1_96[[i]] <- gen_dataset_red1(gamma00, gamma20, gamma40, gamma50, gamma60, 
                          gamma11, gamma21, gamma10_6, gamma10_8,
                          tau0jsq_6, tau0j0k_6, tau0ksq_6, 
                          tau0jsq_8, tau0j0k_8, tau0ksq_8, df=df96)
  models8_1_96[[i]] <- summary(glmmTMB(y ~ condition01 + information01 + age01 +
                                   gender01 + age01*gender01 + age01*condition01 +
                                   age01*information01 + (1 | animal) + (1 | child),
                                   data = datsets8_1_96[[i]],
                                   family = binomial("logit"),
                                   REML = TRUE))
  sig8_1_96[i] <- models8_1_96[[i]]$coefficients[[1]][28]
}
)
sum(as.numeric(unlist(sig8_1_96)<0.05))/1000
#771/1000
```


```{r red2-df96,message=FALSE, warning=FALSE}
set.seed(777)
datsets8_2_96 <- models8_2_96 <- sig8_2_96 <- vector(mode="list", niter)
try(
for (i in 1:(niter)){
  datsets8_2_96[[i]] <- gen_dataset_red2(gamma00, gamma40,  gamma11, 
                                      gamma10_6, gamma10_8, 
                                      tau0jsq_6, tau0j0k_6, tau0ksq_6, 
                                      tau0jsq_8, tau0j0k_8, tau0ksq_8, df=df96)
  models8_2_96[[i]] <- summary(glmmTMB(y ~ condition01 + age01 + age01*condition01 +
                                    (1 | animal) + (1 | child),
                                    data = datsets8_2_96[[i]],
                                    family = binomial("logit"),
                                    REML = TRUE))
  sig8_2_96[i] <- models8_2_96[[i]]$coefficients[[1]][15]
}
)
sum(as.numeric(unlist(sig8_2_96)<0.05))/1000
#840/1000
```
